# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'MVP-Architecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RxSwift'
   pod 'RxCocoa'
   pod 'NSObject+Rx'
   pod 'RxOptional'

  # Pods for MVP-Architecture

  target 'MVP-ArchitectureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVP-ArchitectureUITests' do
    # Pods for testing
  end



end
